service: avengers-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 3

functions:
  hello:
    handler: handler.hello
    memorySize: 256
    timeout: 10

  add:
    handler: add.add
    events:
      - http:
          path: math/add
          method: post
          cors: true
         
